# Jim; Copied this off stack overflow. Not sure about this, does seem to ignore my failing unite tests... Give up!
# Also, I can't get it to run automatically - it can only be triggered from the UI. Shouldn't it run on every commit
# or something?
name: CI pipeline
#on:
#  workflow_dispatch:
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --no-transfer-progress -B compile --file pom.xml