# Jim; I'm giving up on this docker thing. It just fails ,and I've spent about six weeks on this...
name: Docker build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven
        # Jim; Just skipping test for now
        run: mvn --batch-mode --update-snapshots verify

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shopifly:latest

      - name: Build and push Docker image to ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/shopifly
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/shopifly 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1045:$rev
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/shopifly 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1045:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1045:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/1045:latest